// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AmyPearsonVocala.Models
{
    public partial class BookingRequest
    {
        public string HotelName { get; set; }
        public DateTime BookingDate { get; set; }
        public decimal Cost { get; set; }
        public int Status { get; set; }
        public int Id { get; set; }
    }
}